### ISSUE TITLE
Is the morphology data actually eligible for copyright?

### ISSUE THREAD

**Issue by ids1024** [grantham/verba-android#6]
As far as I know, it would not be, as facts cannot be copyrighted, and this seems like it would qualify. But I am not a lawyer, so I could be wrong. But of course, this is not a problem, I just thought it would be worth mentioning.

**Comment by grantham** [comment]
I am also not a lawyer, but I understand that **collections** of information are eligible for copyright.

The copyleft ideas are good -- this one caused me much pain and research about compatibility with other copyleft licenses.

**Comment by ids1024** [comment]
Come to think of it, I think I've heard that. I'll close the issue, since it really makes no difference anyway.
